pengchengsys/home/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

pengchengsys/login_register/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.urls import path
from . import views


app_name = 'login_register'
urlpatterns = [
    path('login/', views.my_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.my_logout, name='logout'),
]

pengchengsys/pengchengsys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('login_register.urls')),
    path('home/', include('home.urls')),
]

pengchengsys/home/models.py
from django.db import models

# Create your models here.

pengchengsys/login_register/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, user_name, phone_num, password=None):
        """
        Creates and saves a User with the given name, phone number and password.
        """
        if not user_name:
            raise ValueError('Users must have a name!')

        user = self.model(
            user_name=user_name,
            phone_num=phone_num,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_name, phone_num, password):
        """
        Creates and saves a superuser with the given name, phone number and password.
        """
        user = self.create_user(
            user_name=user_name,
            phone_num=phone_num,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    user_name = models.CharField(max_length=128, unique=True)
    phone_num = models.BigIntegerField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'user_name'
    REQUIRED_FIELDS = ['phone_num']

    def __str__(self):
        return self.user_name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

pengchengsys/home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def home(request):
    return render(request, 'home/home.html')

pengchengsys/login_register/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from .models import MyUser
import re


def my_login(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'login_register/login.html', context)
    elif request.method == 'POST':
        user_name = request.POST['user_name']
        try:
            user = MyUser.objects.get(user_name=user_name)
            password = request.POST['password']
            user = authenticate(request, username=user_name, password=password)
            if user is not None:
                login(request, user)
                return render(request, 'home/home.html')
            else:
                context["err_info"] = "密码不正确！"
                return render(request, 'login_register/login.html', context)
        except MyUser.DoesNotExist:
            context["err_info"] = "用户名不存在！"
            return render(request, 'login_register/login.html', context)


def my_logout(request):
    logout(request)
    context = {"err_info": "成功退出登录！"}
    return render(request, 'login_register/login.html', context)


def register(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'login_register/register.html', context)
    elif request.method == 'POST':
        user_name = request.POST['user_name']
        try:
            user = MyUser.objects.get(user_name=user_name)
            context["err_info"] = "该用户名已经被注册了！"
            return render(request, 'login_register/register.html', context)
        except MyUser.DoesNotExist:
            phone_num = request.POST['phone_num']
            phone_rule = r'^((13[0-9])|(14[5|7])|(15([0-3]|[5-9]))|(18[0,5-9]))\d{8}$'
            if not re.match(phone_rule, phone_num):
                context["err_info"] = "手机号码输入不正确！"
                return render(request, 'login_register/register.html', context)
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            if password1 != password2:
                context["err_info"] = "两次输入的密码不一致！"
                return render(request, 'login_register/register.html', context)
            else:
                user = MyUser.objects.create_user(user_name, phone_num, password1)
                context["err_info"] = "注册成功！"
                return render(request, 'login_register/register.html', context)

pengchengsys/home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h1>这是首页！</h1>
    <p>请点击如下链接退出登录<br><a href="{% url 'login_register:logout' %}">退出登录</a></p>
<br>
</body>
</html>

pengchengsys/login_register/templates/login_register/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h1>这是首页！</h1>
</body>
</html>

pengchengsys/login_register/templates/login_register/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'login_register/login.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <div class="container">
        <form class="login_form" method="post" action="{% url 'login_register:login' %}">
            {% csrf_token %}
            <div class="login_table_div">
                {% if err_info%}
                    <p id="err_info_p"><strong>{{ err_info }}</strong></p>
                {% endif%}
                <table id="login_table">
                    <tr>
                        <td><label>用户名：</label></td>
                        <td><input type="text" placeholder="请输入用户名" name="user_name"></td>
                    </tr>
                    <tr>
                        <td><label>密码：</label></td>
                        <td><input type="password" placeholder="请输入密码" name="password"></td>
                    </tr>
                </table>
                <div class="button_area">
                    <input type="submit" value="登录">
                    <input type="button" value="重置" id="reset_button">
                </div>
                <div class="link_area">
                    <label>还没有账号？<a id="go_to_register" href="{% url 'login_register:register' %}">前往注册</a></label>
                </div>
            </div>
        </form>
    </div>
</body>
</html>

pengchengsys/login_register/templates/login_register/register.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'login_register/register.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <!--script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script-->
    <script type="text/javascript" src="{% static 'login_register/register.js' %}"></script>
</head>
<body>
    <div class="container">
        <form class="register_form" method="post" action="{% url 'login_register:register' %}">
            {% csrf_token %}
            <div class="register_table_div">
                {% if err_info%}
                    <p id="err_info_p"><strong>{{ err_info }}</strong></p>
                {% endif%}
                <table id="register_table">
                    <tr>
                        <td><label>用户名：</label></td>
                        <td><input type="text" name="user_name" id="user_name_input"></td>
                    </tr>
                    <tr>
                        <td><label>手机号码：</label></td>
                        <td><input type="text" name="phone_num" id="phone_num_input"></td>
                    </tr>
                    <tr>
                        <td><label>密码：</label></td>
                        <td><input type="password" name="password1" id="password1_input"></td>
                    </tr>
                    <tr>
                        <td><label>确认密码：</label></td>
                        <td><input type="password" name="password2" id="password2_input"></td>
                    </tr>
                </table>
                <div class="button_area">
                    <input type="submit" value="注册" id="register_button">
                    <button type="button" id="reset_button" onclick="reset()">重置</button>
                </div>
                <div class="link_area">
                    <label>已有账号？<a id="go_to_login" href="{% url 'login_register:login' %}">前往登录</a></label>
                </div>
            </div>
        </form>
    </div>

    <!--script>
        function reset(){
            document.getElementById("user_name_input").innerHTML = "";
        }
    </script-->
</body>
</html>